import { Main } from 'next/document'
import Head from 'next/head'
import Image from 'next/image'
import { agents } from '../components/lib/agents'
import { Pagination } from '../components/Pagination'
import TopRatedAgent from '../components/topRatedAgent'
import styles from '../styles/Home.module.css'

export default function Home() {

  const topRatedAgents = agents.map((agent, index) => {
    return <TopRatedAgent agent={agent} />
  })

  return (
    <div className=''>
      <Head>
        <title>AB landing page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,500;1,600&display=swap" rel="stylesheet"/>
      </Head>

      <main className='p-12'>
  
        {<Pagination cards={topRatedAgents}/>}
      </main>

    </div>
  )
}
