import { latesttype } from "./types";

export const latest: latesttype[] = [
  {
    coverPhoto: "/images/state1.png",
    uploader: 1,
    title: "How to get multiple offers on your home",
    status: "Selling",
    date: "MARCH 21, 2022",
    readby: 5,
  },
  {
    coverPhoto: "/images/state2.png",
    uploader: 2,
    status: "Buying",
    title: "10 home buying tips for first-time home buyers",
    date: "MARCH 21, 2022",
    readby: 5,
  },
  {
    coverPhoto: "/images/state3.png",
    uploader: 3,
    title: "15 simple and relaxing  decor ideas to transform your home ",
    status: "Selling",
    date: "MARCH 21, 2022",
    readby: 5,
  },
  {
    coverPhoto: "/images/state1.png",
    uploader: 1,
    title: "How to get multiple offers on your home",
    status: "Selling",
    date: "MARCH 21, 2022",
    readby: 5,
  },
  {
    coverPhoto: "/images/state2.png",
    uploader: 2,
    status: "Buying",
    title: "10 home buying tips for first-time home buyers",
    date: "MARCH 21, 2022",
    readby: 5,
  },
  {
    coverPhoto: "/images/state2.png",
    uploader: 2,
    status: "Buying",
    title: "10 home buying tips for first-time home buyers",
    date: "MARCH 21, 2022",
    readby: 5,
  },
  {
    coverPhoto: "/images/state1.png",
    uploader: 1,
    title: "How to get multiple offers on your home",
    status: "Selling",
    date: "MARCH 21, 2022",
    readby: 5,
  },
  {
    coverPhoto: "/images/state2.png",
    uploader: 2,
    status: "Buying",
    title: "10 home buying tips for first-time home buyers",
    date: "MARCH 21, 2022",
    readby: 5,
  },
  {
    coverPhoto: "/images/state3.png",
    uploader: 3,
    title: "15 simple and relaxing  decor ideas to transform your home ",
    status: "Selling",
    date: "MARCH 21, 2022",
    readby: 5,
  },
  {
    coverPhoto: "/images/state1.png",
    uploader: 1,
    title: "How to get multiple offers on your home",
    status: "Selling",
    date: "MARCH 21, 2022",
    readby: 5,
  },
  {
    coverPhoto: "/images/state2.png",
    uploader: 2,
    status: "Buying",
    title: "10 home buying tips for first-time home buyers",
    date: "MARCH 21, 2022",
    readby: 5,
  },
  {
    coverPhoto: "/images/state2.png",
    uploader: 2,
    status: "Buying",
    title: "10 home buying tips for first-time home buyers",
    date: "MARCH 21, 2022",
    readby: 5,
  }
];
